name: Compilation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  compiler:
    name: Compiler avec nexe
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Installer pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer
        run: pnpm install

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.nexe
          key: ${{ runner.os }}-nexe

      - name: Compiler
        run: pnpm compiler

      - name: Vérifier compilation
        run: ls paquets/exec
