name: Serveur WS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests-et-couverture:
    name: On test le serveur
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer
        run: pnpm install

      - name: Vérifier les tests
        run: pnpm couverture

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
